### ISSUE TITLE
doesn't seem to work...

### ISSUE THREAD

**Issue by ukeboyska** [ptrkcsk/fa-wp-admin-menu-icons#1]
hi there - awesome plugin in theory, but after installing it and following the directions the icons appear as the normal, default push pin.

the HTML doesn't seem to be altered at all. for example, i'm using "'menu_icon'=>'fa-bullhorn'," in my custom post type, but then the HTML is: "`<div class="wp-menu-image dashicons-before dashicons-admin-post"><br></div>`" ...

i'm using WordPress 4.9-alpha-40900

**Comment by ptrkcsk** [comment]
Thanks for the report @ukeboyska. I last tested the plugin with WP v4.7.3. I'll do some debugging in the next few days.

**Comment by ptrkcsk** [comment]
@ukeboyska, were you installing the plugin via WordPress? It turns out the icons directory was empty! 😱  (It was my first time using Subversion.)

If you installed the plugin via WordPress, try updating to at least v1.0.1.

**Comment by ukeboyska** [comment]
Yes I did - thanks for updating I'll try this agian later :)

**Comment by ukeboyska** [comment]
fixed! thanks!

**Comment by ptrkcsk** [comment]
Great!
