### ISSUE TITLE
compatible with CPT UI plugin?

### ISSUE THREAD

**Issue by dylantuohy** [ptrkcsk/fa-wp-admin-menu-icons#7]
Hello! I found this plugin when I saw your comment that it is compatible with the CPT UI plugin:

(https://github.com/WebDevStudios/custom-post-type-ui/issues/647#issuecomment-353807333)

However, it doesn't seem to work with the most recent versions (CPT UI 1.5.8, FA WP Admin Menu Icons 2.8.0)

FA icons appear correctly when creating a post type with `register_post_type`, but not when using the Menu Icon field in CPT UI.  It results in a broken image:

`<img src="http://fas%20fa-thumbs-up" alt="">`

**Comment by ptrkcsk** [comment]
Thanks for the issue, @dylantuohy !

I just pushed a new version which [includes](https://github.com/ptrkcsk/fa-wp-admin-menu-icons/commit/f5cb168d1f8169134be75ba6e093a78d636e442e) a fix. Try it out and let me know if it works!

**Comment by dylantuohy** [comment]
New version works great! Thanks @ptrkcsk

**Comment by ptrkcsk** [comment]
Glad to hear it!
